apiVersion: apps/v1
kind: Deployment
metadata:
  name: templates-ansible-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: templates-ansible-operator
  template:
    metadata:
      labels:
        name: templates-ansible-operator
    spec:
      serviceAccountName: templates-ansible-operator
      containers:
        - name: templates-ansible-operator
          # Replace this with the built image name
          image: registry:5000/templates-ansible-operator:v0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "templates-ansible-operator"
